BINARY_CLIENT_BIN=$(INSTALL_PREFIX)/cluster-cli
GOAGEN_BIN=$(VENDOR_DIR)/github.com/goadesign/goa/goagen/goagen

GO_BIN_NAME := go
DOCKER_BIN_NAME=docker
CHECK_GOPATH_BIN := $(INSTALL_PREFIX)/check_gopath
