BINARY_CLIENT_BIN=$(INSTALL_PREFIX)/cluster-cli.exe
GOAGEN_BIN=$(VENDOR_DIR)/github.com/goadesign/goa/goagen/goagen.exe

GO_BIN_NAME := go.exe
DOCKER_BIN_NAME=docker.exe
CHECK_GOPATH_BIN := $(INSTALL_PREFIX)/check_gopath.exe
